from dataclasses import dataclass
from typing import Any, ClassVar

from .constants import CommandTags, ResponseTags, SecurityConstants
from .exceptions import PayloadValidationError
from .payload import OsdpBasePayload


@dataclass
class OsdpKeysetPayload(OsdpBasePayload):
    """
    osdp_KEYSET payload for secure channel base key management.

    Byte structure (3 + key_length bytes):
    [0] key_type - Key type identifier (0x01 for SCBK)
    [1] key_length - Length of key data in bytes
    [2...2+key_length-1] key_data - Key data bytes
    """

    key_type: int
    """
    Key type identifier (0x01 for SCBK)
    """

    key_length: int
    """
    Length of the key data in bytes
    """

    key_data: bytes
    """
    Key data bytes
    """

    MIN_DATA_LEN: int = 3

    def __post_init__(self):
        """Validate field values after initialization."""
        if self.key_type < 0 or self.key_type > 255:
            raise PayloadValidationError(f"Invalid key_type: {self.key_type}")
        if self.key_length < 0 or self.key_length > 255:
            raise PayloadValidationError(f"Invalid key_length: {self.key_length}")
        if len(self.key_data) != self.key_length:
            raise PayloadValidationError(f"key_length ({self.key_length}) does not match key_data length ({len(self.key_data)})")
        if self.key_type == SecurityConstants.SCBK and self.key_length != 16:
            raise PayloadValidationError(f"SCBK key must be 16 bytes, got {self.key_length}")

    def to_bytes(self) -> bytes:
        data = bytearray([self.key_type, self.key_length])
        data.extend(self.key_data)
        return bytes(data)

    @classmethod
    def from_bytearray(cls, ba: bytearray):
        if len(ba) < OsdpKeysetPayload.MIN_DATA_LEN:
            raise PayloadValidationError("osdp_KEYSET payload too short")

        key_type = ba[0]
        key_length = ba[1]

        if len(ba) != OsdpKeysetPayload.MIN_DATA_LEN - 1 + key_length:
            raise PayloadValidationError("osdp_KEYSET payload length mismatch")

        return OsdpKeysetPayload(
            tag=CommandTags.KEYSET,
            key_type=key_type,
            key_length=key_length,
            key_data=bytes(ba[2 : 2 + key_length]),
        )

    def _get_format_fields(self, format_short: bool = False) -> dict[str, Any]:
        """
        Define format fields for KEYSET payload.

        Note: Does not expose key_data for security reasons.

        :param format_short: If True, return short format fields; if False, return long format fields
        :return: Dict mapping field_name -> config dict
        """
        fields = {
            "key_type": {"name": "Key Type", "transform": "hex", "width": 2},
            "key_length": {"name": "Key Length"},
        }
        return fields


@dataclass
class OsdpChlngPayload(OsdpBasePayload):
    """
    osdp_CHLNG payload for secure channel challenge initiation.

    Byte structure (8 bytes):
    [0...7] rnd - 8-byte random number (RNDA) generated by the controller
    """

    rnd: bytes
    """
    8-byte random number (RNDA) generated by the controller
    """

    DATA_LEN: int = 8

    def __post_init__(self):
        """Validate field values after initialization."""
        if len(self.rnd) != self.DATA_LEN:
            raise PayloadValidationError(f"rnd must be {self.DATA_LEN} bytes, got {len(self.rnd)}")

    def to_bytes(self) -> bytes:
        return self.rnd

    @classmethod
    def from_bytearray(cls, ba: bytearray):
        if len(ba) != OsdpChlngPayload.DATA_LEN:
            raise PayloadValidationError("osdp_CHLNG payload bad length")

        return OsdpChlngPayload(
            tag=CommandTags.CHLNG,
            rnd=bytes(ba),
        )


@dataclass
class OsdpScryptPayload(OsdpBasePayload):
    """
    osdp_SCRYPT payload for server cryptogram verification.

    Byte structure (16 bytes):
    [0...15] server_cryptogram - 16-byte server cryptogram for authentication
    """

    server_cryptogram: bytes
    """
    16-byte server cryptogram for authentication
    """

    DATA_LEN: int = 16

    def __post_init__(self):
        """Validate field values after initialization."""
        if len(self.server_cryptogram) != self.DATA_LEN:
            raise PayloadValidationError(f"server_cryptogram must be {self.DATA_LEN} bytes, got {len(self.server_cryptogram)}")

    def to_bytes(self) -> bytes:
        return self.server_cryptogram

    @classmethod
    def from_bytearray(cls, ba: bytearray):
        if len(ba) != OsdpScryptPayload.DATA_LEN:
            raise PayloadValidationError("osdp_SCRYPT payload bad length")

        return OsdpScryptPayload(
            tag=CommandTags.SCRYPT,
            server_cryptogram=bytes(ba),
        )


@dataclass
class OsdpCcryptPayload(OsdpBasePayload):
    """
    osdp_CCRYPT payload for client cryptogram response in secure channel.

    Byte structure (32 bytes):
    [0...7] client_id - 8-byte Client's Unique Identifier (cUID)
    [8...15] random_number - 8-byte PD's random number generated (RND.B)
    [16...31] client_cryptogram - 16-byte client cryptogram for authentication
    """

    client_id: bytes
    """
    8-byte Client's Unique Identifier (cUID)
    """

    random_number: bytes
    """
    8-byte PD's random number generated (RND.B)
    """

    client_cryptogram: bytes
    """
    16-byte client cryptogram for authentication
    """

    DATA_LEN: int = 32
    CLIENT_ID_LEN: int = 8
    RANDOM_NUMBER_LEN: int = 8
    CRYPTOGRAM_LEN: int = 16

    TITLE: ClassVar[str] = "CCRYPT Response"
    """
    Title for this payload type.
    """

    def __post_init__(self):
        """Validate field values after initialization."""
        if len(self.client_id) != self.CLIENT_ID_LEN:
            raise PayloadValidationError(f"client_id must be {self.CLIENT_ID_LEN} bytes, got {len(self.client_id)}")
        if len(self.random_number) != self.RANDOM_NUMBER_LEN:
            raise PayloadValidationError(f"random_number must be {self.RANDOM_NUMBER_LEN} bytes, got {len(self.random_number)}")
        if len(self.client_cryptogram) != self.CRYPTOGRAM_LEN:
            raise PayloadValidationError(f"client_cryptogram must be {self.CRYPTOGRAM_LEN} bytes, got {len(self.client_cryptogram)}")

    def to_bytes(self) -> bytes:
        data = bytearray(self.client_id)
        data.extend(self.random_number)
        data.extend(self.client_cryptogram)
        return bytes(data)

    @classmethod
    def from_bytearray(cls, ba: bytearray):
        if len(ba) != OsdpCcryptPayload.DATA_LEN:
            raise PayloadValidationError("osdp_CCRYPT payload bad length")

        return OsdpCcryptPayload(
            tag=ResponseTags.CCRYPT,
            client_id=bytes(ba[0:8]),
            random_number=bytes(ba[8:16]),
            client_cryptogram=bytes(ba[16:32]),
        )

    def _get_format_fields(self, format_short: bool = False) -> dict[str, Any]:
        fields = {
            "_status": {"name": "Status", "compute": lambda p: "Continuing secure channel"},
        }
        if not format_short:
            fields = {
                **fields,
                "tag": {"name": "Message ID", "transform": "hex", "width": 2},
                "_status": {"name": "Status", "compute": lambda p: "Continuing secure channel establishment"},
            }
        return fields


@dataclass
class OsdpRmaciPayload(OsdpBasePayload):
    """
    osdp_RMAC_I payload for initial MAC value in secure channel.

    Byte structure (16 bytes):
    [0...15] mac_i - 16-byte MAC array - initial MAC value
    """

    mac_i: bytes
    """
    16-byte MAC array - initial MAC value
    """

    DATA_LEN: int = 16

    TITLE: ClassVar[str] = "RMAC_I Response"
    """
    Title for this payload type.
    """

    def __post_init__(self):
        """Validate field values after initialization."""
        if len(self.mac_i) != self.DATA_LEN:
            raise PayloadValidationError(f"mac_i must be {self.DATA_LEN} bytes, got {len(self.mac_i)}")

    def to_bytes(self) -> bytes:
        return self.mac_i

    @classmethod
    def from_bytearray(cls, ba: bytearray):
        if len(ba) != OsdpRmaciPayload.DATA_LEN:
            raise PayloadValidationError("osdp_RMAC_I payload bad length")

        return OsdpRmaciPayload(
            tag=ResponseTags.RMAC_I,
            mac_i=bytes(ba),
        )

    def _get_format_fields(self, format_short: bool = False) -> dict[str, Any]:
        fields = {
            "_status": {"name": "Status", "compute": lambda p: "Completing secure channel"},
        }
        if not format_short:
            fields = {
                **fields,
                "tag": {"name": "Message ID", "transform": "hex", "width": 2},
                "_status": {"name": "Status", "compute": lambda p: "Completing secure channel establishment"},
            }
        return fields
